import React from "react";

function MVP() {
  return (
    <div className="hero-section container text-white">
      <div
        className="  card bg_black mt-5 mb-5   p-3"
        style={{ backgroundColor: "#0090f8" }}
      >
        <div className="  card-body  d-lg-flex flex-wrap align-items-center justify-content-between gap-3">
          <h2 className="text-white">WMP</h2>
          <p className="pt- text-white  fw-light justify_text">
            Our project's self-developed digital card and pass that runs on the
            blockchain. They run on the polygron blockchain and can be purchased
            with the stable cryptocurrency USDT. In the future, we will work on
            the development of our own stable cryptocurrency, so we will
            implement WMP purchase with WMP stable coin. Each WMP has a unique
            look and unique features. Among their features, it stands out for
            the first time in the world that it simply ensures the booking of
            accommodation via the blockchain and at the same time earn a passive
            income. Rewards are generated by staking WMPs. During the staking
            time, the price of WMP is fully covered and generates extra profit.
            Our WMPs have many variant of diverse collection and each collection
            consist of five WMPs. You can choose a duration of stay and number
            of people participating in travel. All WMPs can be transferred to or
            sold between individuals. It is possible to transfer part of the
            trip to another person. The reservation is made based on the wallet
            address of the WMP and the name of the booker. Thus, all you have to
            do is place your name on the place of the traveling person. Each WMP
            is intended for several people, but we only need the name of the WMP
            owner or to whom we offered it. The trip can be used at any time, of
            course, if our reservation is available for that period. We are sure
            that you will find other free times that suit everyone. If you do
            not travel, it has no effect on the staking option. As long as you
            are only looking for passive income, it is perfectly fine if you do
            not want to use WMPs for travel. Everyone can use WMPs as they like.
            From time to time, there will be limited series WMPs that do not
            contain a collection, only 1 item of them is deployed. These special
            ones last more days than the collection of WMPs. Also include
            several special programs and events. In addition, the project's tour
            guide holds programs for us every day, includes special yoga and
            meditation programs that allow you to completely turn off your mind
            and surrender to peace. In case you want to travel for 10 days, 2
            weeks or more, it is possible by combining several WMPs in the
            collection. For example, two WMP s of 5 days arevalid for 10 days
            and so on. Different WMPs contain extra usage. There are three such
            things. Games, programs, events. Those who are suitable for the
            games can win various prizes, which we launch from time to time.
            Passes with programs entitle our guests to one or more programs,
            such as hiking, skiing, diving and others. Marked with events, it
            invites our guests to a pleasant dinner or lunch. Event and program
            passes are valid for one or more occasions. The price list of the
            released WMP collections and passive income tables from staking can
            be found in the whitepaper.
          </p>
        </div>
      </div>
    </div>
  );
}

export default MVP;
